.catalog:
  name: Prestashop
  version: v0.1
  description: Prestashop
  questions:
    - variable: "PORT"
      type: "string"
      label: "PORT"
      description: Frontend Port of Prestashop
      default: 80
    - variable: "MYSQL_ROOT_PASSWORD"
      type: "string"
      label: "MYSQL_ROOT_PASSWORD"
      description: Password
      default: "presta12"
    - variable: "MYSQL_DATABASE"
      type: "string"
      label: "MYSQL_DATABASE"
      description: database name
      default: "prestashop"
    - variable: "MYSQL_USER"
      type: "string"
      label: "MYSQL_USER"
      description: database user
      default: "prestashop"
    - variable: "MYSQL_PASSWORD"
      type: "string"
      label: "MYSQL_PASSWORD"
      description: database Password
      default: "presta12"
    - variable: NET
      description: "select Network type"
      label: "Network"
      type: enum   
      options:
        - host
        - managed
        - none
      required: true
      default: "host"
prestashop:
  scale: 1
mysql:
  scale: 1