version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.1
    ports:
      - "${SERVER_PORT}:5601"
    environment:
      SERVER_NAME: ${SERVER_NAME}
      ELASTICSEARCH_URL:  http://${ELASTICSEARCH_LINK}:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme