.catalog:
  name: Plex Server
  version: v0.1
  description: Plex Media Server
  questions:
    - variable: "PORT"
      type: "string"
      label: "PORT"
      description: Frontend Port of Plex
      default: 32400
    - variable: "PATHCONFIG"
      type: "string"
      label: "Config Path"
      description: persistang Path to your Plex Config (/home/nick/plex, ...)
      default: '/home'
    - variable: "PATHMEDIA"
      type: "string"
      label: "Media Path"
      description: the Path to your library (/data/media, or a nfs mount /mnt:/media, ...)
      default: '/data/media'
    - variable: "PUID"
      type: "string"
      label: "PUID"
      description: GroupID (not required)
    - variable: "PGID"
      type: "string"
      label: "PGID"
      description: PGID (not required)
Plex:
  scale: 1