.catalog:
  name: Plex Server
  version: v0.6
  description: Plex Media Server
  questions:
    - variable: "PORT"
      type: "string"
      label: "PORT"
      description: Frontend Port of Plex external:internal
      default: 32400:32400
    - variable: "PATHCONFIG"
      type: "string"
      label: "Config Path"
      description: persistant Path to your Plex Config (/home/nick/plex, ...)
      default: '/var/plex'
    - variable: "PATHMEDIA"
      type: "string"
      label: "Media Path"
      description: persistant Path to your Plex Config (/home/nick/plex, ...)
      default: '/mnt/ssd1'
    - variable: "PATHMETADATA"
      type: "string"
      label: "Metadata Path"
      description: persistant Path to your Plex Config (/home/nick/plex, ...)
      default: '/mnt/ssd2'
    - variable: "PATHTV"
      type: "string"
      label: "TV Path"
      description: the Path to your TV library (/media, or a nfs mount /mnt, ...)
      default: '/mnt/TV'
    - variable: "PATHMOVIES"
      type: "string"
      label: "Movies Path"
      description: the Path to your Movies library (/media, or a nfs mount /mnt, ...)
      default: '/mnt/Movies'
    - variable: "PATHMUSIC"
      type: "string"
      label: "Music Path"
      description: the Path to your Music library (/media, or a nfs mount /mnt, ...)
      default: '/mnt/Music'
    - variable: "PATHFLAC"
      type: "string"
      label: "FLAC Path"
      description: the Path to your FLAC library (/media, or a nfs mount /mnt, ...)
      default: '/mnt/FLAC'
    - variable: "PUID"
      type: "string"
      label: "PUID"
      description: GroupID (not required)
      default: 1100
    - variable: "PGID"
      type: "string"
      label: "PGID"
      description: PGID (not required)
      default: 1100
    - variable: "NET"
      description: "select Network type"
      label: "Network"
      type: "enum"
      options:
        - host
        - managed
        - none
      required: true
      default: "host"
services:
  plex:
    scale: 1
    start_on_create: true
