version: '2'
.catalog:
  name: "ELK"
  version: "5.2.2"
  description: "ELK Stack --> vm_map_max_count must be 262144 --> https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html"
services:
  elasticsearch1:
    scale: 1
    start_on_create: true
  elasticsearch2:
    scale: 1
    start_on_create: true
  kibana:
    scale: 1
    start_on_create: true